### ISSUE TITLE
Custom Properties

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/FAU-Elemental#70]
Im CSS sollten stets Custom Properties verwendet werden, wenn es um Variablen geht_
Feste Werte für Farben, Paddings, Margins, Font-Sizes etc. sollten generell nur via Custom Propertiesbverwendet werden.
SASS Variablen sollten nicht nehr verwendet werden. Hardcodierte Anweisungen irgendwo in der SASS Files sind zu vermeiden.

Folgende Custom Proerties sollte das Theme grundsätzlich als Basis im :root {} definieren und nutzen:

Vorbild: https://github.com/RRZE-Webteam/FAU-Einrichtungen/blob/master/src/sass/_custom-properties.scss

```css

:root {

 /*  Colors: */

  --color-primary-ci-hell: #04316A;
  --color-primary-ci-hell-kontrast: #fff;
  --color-primary-ci-hell2: #CED9E7;
  --color-primary-ci-hell2-kontrast: #000;
  --color-primary-dunkler: #004A9F;
  --color-primary-dunkler-kontrast: #fff;
  --color-primary-dunkelste: #041E42;
  --color-primary-dunkelste-kontrast: #fff;
  --color-zentral-ci-hell: #04316A;
  --color-zentral-ci-hell-kontrast: #fff;
  --color-zentral-ci-hell2: #CED9E7;
  --color-zentral-ci-hell2-kontrast: #000;
  --color-zentral-dunkler: #004A9F;
  --color-zentral-dunkler-kontrast: #fff;
  --color-zentral-dunkelste: #041E42;
  --color-zentral-dunkelste-kontrast: #fff;
  --color-phil-ci-hell: #FDB735;
  --color-phil-ci-hell-kontrast: #000;
  --color-phil-ci-hell2: #F4E8CB;
  --color-phil-ci-hell2-kontrast: #000;
  --color-phil-dunkler: #e87722;
  --color-phil-dunkler-kontrast: #000;
  --color-phil-dunkelste: #963B2F;
  --color-phil-dunkelste-kontrast: #fff;
  --color-med-ci-hell: #18B4F1;
  --color-med-ci-hell-kontrast: #000;
  --color-med-ci-hell2: #B9D9EC;
  --color-med-ci-hell2-kontrast: #000;
  --color-med-dunkler: #005287;
  --color-med-dunkler-kontrast: #fff;
  --color-med-dunkelste: #003E61;
  --color-med-dunkelste-kontrast: #fff;
  --color-nat-ci-hell: #7BB725;
  --color-nat-ci-hell-kontrast: #000;
  --color-nat-ci-hell2: #CFE0D8;
  --color-nat-ci-hell2-kontrast: #000;
  --color-nat-dunkler: #266141;
  --color-nat-dunkler-kontrast: #fff;
  --color-nat-dunkelste: #14462D;
  --color-nat-dunkelste-kontrast: #fff;
  --color-rw-ci-hell: #C50F3C;
  --color-rw-ci-hell-kontrast: #fff;
  --color-rw-ci-hell2: #F2DED1;
  --color-rw-ci-hell2-kontrast: #000;
  --color-rw-dunkler: #971B2F;
  --color-rw-dunkler-kontrast: #fff;
  --color-rw-dunkelste: #662938;
  --color-rw-dunkelste-kontrast: #fff;
  --color-tf-ci-hell: #8C9FB1;
  --color-tf-ci-hell-kontrast: #000;
  --color-tf-ci-hell2: #D3DDE6;
  --color-tf-ci-hell2-kontrast: #000;
  --color-tf-dunkler: #2F586E;
  --color-tf-dunkler-kontrast: #fff;
  --color-tf-dunkelste: #204251;
  --color-tf-dunkelste-kontrast: #fff;


  --color-Text: #222;
  --color-MainBackground: #fff;
  --color-StandardHellgrau: #e9edf2;
  --color-StandardHellgrau-Hover: #d3dde6;
  --color-PrintMain: #000;
  --color-branding-primary: #04316A;
  --color-branding-primary-kontrast: #fff;
  --color-branding-zentral: #04316A;
  --color-branding-phil: #FDB735;
  --color-branding-med: #18B4F1;
  --color-branding-nat: #7BB725;
  --color-branding-rw: #C50F3C;
  --color-branding-tf: #8C9FB1;
  --color-FAU: #04316A;
  --color-primary-basis: var(--color-branding-primary);
  --color-primary-basis-kontrast: var(--color-branding-primary-kontrast);
  --color-MetaHomeBackground: #d4d4d4;
  --color-MetaHover: #264c7b;
  --color-MetaText: #fff;

  --color-links: #222;
  --color-links-underline: #04316A;
  --color-links-hover: #04316A;
  --color-button-text: #fff;
  --color-button-bg: #04316A;
  --color-button-hover-text: #fff;
  --color-button-hover-bg: #041E42;
  --color-ghostbutton-hover-text: #fff;
  --color-ghostbutton-hover-bg: #04316A;
  --color-footer-bg: #04316A;
  --color-footer-text: #fff;
  --color-hero-bg: #04316A;
  --color-hero-text: #fff;

/* Font Sizes */
  --font-size-xs: 0.76rem;
  --font-size-sm: 0.875rem;
  --font-size-tiny: 0.938rem;
  --font-size-normal: 1rem;
  --font-size-lg: 1.125rem;
  --font-size-xl: 1.25rem;
  --font-size-xxl: 1.5rem;
  --font-size-slider-title: 1.75rem;
  --font-size-h1: 1.8125rem;
  --font-size-h1-sm: clamp(var(--font-size-normal), calc(var(--font-size-h1) - (2 / 16 * 1rem)), var(--font-size-h1));
  --font-size-h1-sidebar: clamp(var(--font-size-normal), calc(var(--font-size-h1) - (5 / 16 * 1rem)), var(--font-size-h1));
  --font-size-h2: 1.5rem;
  --font-size-h2-sm: clamp(var(--font-size-normal), calc(var(--font-size-h2) - (2 / 16 * 1rem)), var(--font-size-h2));
  --font-size-h2-sidebar: clamp(var(--font-size-normal), calc(var(--font-size-h2) - (3 / 16 * 1rem)), var(--font-size-h2));
  --font-size-h3: 1.3125rem;
  --font-size-h3-sm: clamp(var(--font-size-normal), calc(var(--font-size-h3) - (2 / 16 * 1rem)), var(--font-size-h3));
  --font-size-h3-sidebar: var(--font-size-h3-sm);
  --font-size-h4: 1.1875rem;
  --font-size-h4-sm: clamp(var(--font-size-normal), calc(var(--font-size-h4) - (2 / 16 * 1rem)), var(--font-size-h4));
  --font-size-h4-sidebar: var(--font-size-h4-sm);
  --font-size-h5: 1.125rem;
  --font-size-h5-sm: clamp(var(--font-size-normal), calc(var(--font-size-h5) - (2 / 16 * 1rem)), var(--font-size-h5));
  --font-size-h5-sidebar: var(--font-size-h5-sm);
  --font-size-h6: 1.0625rem;
  --font-size-h6-sm: clamp(var(--font-size-normal), calc(var(--font-size-h6) - (2 / 16 * 1rem)), var(--font-size-h6));
  --font-size-h6-sidebar: var(--font-size-h6-sm);
  --base-line-height: 1.5;

  /* Fonts: */
  --font-family-default: Roboto, FAU Chimera, sans-serif;
  --font-family-serif: Georgia, Times New Roman, Times, serif;
  --font-family-monospace: Menlo, Monaco, Consolas, Courier New, monospace;
  --font-family-FAU-Logo: FAU Chimera, sans-serif;

  /* Margins, Paddings  */
  --border-radius: 0px;
  --border-radius-buttons: 0px;
  --devider-height: 4px;
  --width-gutter: 30px;
  --width-gutter-half: 15px;
  --width-gutter-third: 10px;

}
```
